### ISSUE TITLE
Invalid position in Completions

### ISSUE THREAD

**Issue by mjshashank** [sourcegraph/go-langserver#257]
I'm working on a custom client with this language server.

When I requests for a completion with the files contents as:
```im``` and line as 0 and character as 2, I get ```error: go completion error: Error: invalid position: (character 2 is beyond first line boundary)```

But when I make a request with a blank line or space appended as:
```im\n``` or ```im ``` and the same line, character values of 0,2 I receive accurate completions.

Is this a known issue or expected behaviour? Else, what am I doing wrong here?

**Comment by lloiser** [comment]
This is fixed in #83 with commit https://github.com/sourcegraph/go-langserver/pull/83/commits/8b3e27eddc852566b372c0e77472b1a1d9e11f37#diff-78179d406a671306d86895d9604fca17

**Comment by butterflyfish** [comment]
i'm looking forward to address this problem also. thank you!

**Comment by butterflyfish** [comment]
this issue still exists on neovim with plugin [ncm2](https://github.com/ncm2/ncm2) and [LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim)

**Comment by fntlnz** [comment]
I have the exact same problem if I start `go-langserver` without arguments but I was able to have it working with the following arguments:

```bash
go-langserver --gocodecompletion --freeosmemory false
```

**Comment by mikefaille** [comment]
I get this problem too using Emacs 27-trunk, eglot (https://github.com/joaotavora/eglot) as client and completion-at-point as autocompletion system (to test).

**Comment by mikefaille** [comment]
I get this problem too using Emacs 27-trunk + eglot. To fix it, I delete eglot and jsonrpc from emacs using `package-delete` function. I update go-languageserver and I reinstall eglot. Then everything work without tweaks special tweaks.
